//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFCApp.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAddress
    {
        public string Client { get; set; }
        public string Address { get; set; }
        public long ID { get; set; }
    
        public virtual Client Client1 { get; set; }
    }
}
